#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.1.{build}-{branch}

# branches to build  
branches:
  only:
  - master

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Build worker image (VM template)
image:
 - Visual Studio 2017

# Use MongoDb as database
services:
 - mongodb

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build Configuration, i.e. Debug, Release, etc.
configuration:
 - Release
 - Debug

# build platform, i.e. x86, x64, Any CPU. This setting is optional
platform:
  - Any CPU

before_build:
 - nuget restore "WaesDiff"
 - appveyor-retry dotnet restore "WaesDiff" -v Minimal

build_script:
  - dotnet build "WaesDiff/WaesDiff.WebAPI" -c %CONFIGURATION% --version-suffix %LABEL%
  - dotnet build "WaesDiff/WaesDiff.Domain" -c %CONFIGURATION% --version-suffix %LABEL%
  - dotnet build "WaesDiff/WaesDiff.Infrastructure" -c %CONFIGURATION% --version-suffix %LABEL%
  
  - dotnet build "WaesDiff/WaesDiff.Tests" -c %CONFIGURATION% --version-suffix %LABEL%
  
after_build:
  - dotnet build "WaesDiff" -c %CONFIGURATION% --version-suffix %LABEL%


#---------------------------------#
#    environment configuration    #
#---------------------------------#
  
# environment variables

# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: true
  project_feed: true

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:

# Email
- provider: Email
  to:
  - douglasmathias@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
  
  #---------------------------------#
#       tests configuration       #
#---------------------------------#

# scripts to run before tests
before_test:
 - choco install opencover.portable
 - choco install codecov

# to run your custom scripts instead of automatic tests
test_script:
  - dotnet test "WaesDiff/WaesDiff.Tests" -c %CONFIGURATION%  

  - OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test /p:DebugType=full Tests/UnitTest" -output:"UnitTestResult.xml" -oldstyle
  
# scripts to run after tests
#after_test:
# - codecov -f "UnitTestAPIResult.xml" -t 81c4ac46-b5bc-4d0d-8c4f-4de04812e6e3 
